spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tomatomall
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.engine.transaction.internal.TransactionImpl: debug
    org.springframework.transaction: trace
    com.example.tomatomall: debug


alipay:
  app-id: 2021000148611573
  private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQClfl4SG9lOl3jl7TiYZbjzZdhg4n/+zvM8PQwAF2Gmze2TRfB4O6kyHCPhmVxgXlXoPtWuqxsv/SNdJDfZM+GqiIdo54w6FnIISy6vLZzdDly6pHPn+yIV5Y4CQuEt94vxNc2ETb1gMgTMMQU0XG2ChEjKJJ4qHeNnP5gX3T0V26V9aDUp/ZSx6RSbySu/0OZi/3vVountgaagcx+a6uxSJnEcMCnE7k4v2t9PDiBjklSoByjvs9xEH+hCc5ts5St8IF1BfZy+JM9IsSEQEf99eGcaPXTtcyGi3krlsGKO9jxl5iMCzXJFTxci6e8p0NJVcXo8p7ij51PNfGB7+3VXAgMBAAECggEAKFpDvc6kkhFFHWtWXXKQQmkW9ajE5PC5RnrsLimFWhLkVwC6vdZuTxWleiDW8XiPIe4QVGLMYksrEE8AfymzYM2hlua+vnsymusaGwTYNt6FpczrpikKCqTKl6qPFZJCwTIJRrVd89K+cLuTNU1ENori5MdA+awIAujywP7lIiriBTcxMmt7BM5MtqZhSu4lSVaygriW57VAllNX+48wxAF/kJ1rusXjKTZipKu9c9jT7q3D2mVy8getOG1EOo/pq7ko4HwoJCukRja9zR2UwAhPD44C4M0Kqpp3Mh33XD2zMtcHTG4fsW+6w6WgOGHLhlEnRM/cmmmEXOtPk33XoQKBgQD9ZgfNk6lXzceh6Ac0HW5p1SyHfyu0vCV2LfvXcmsDww0i9l1cNaHDFctr8l2rH5VrgfYvdWozIol/bcLQCjVqaiCa59/q7H97sSTPkDOw9/N9n1VNrkTk7nvb+9y8kiEaFZ5m7I0WeeMn2zUe3P04LYGY6AVxdSvvF2Y+T7zFAwKBgQCnMU9BsKe2D+BRflRTwrCpKXmQq6R8glrWveOrHY4hBsOjFYgEFr0Je2/1I68UEAvotUIVWZYFzKOvoz64rUYErj69hIh5W+8jwi1Z9dmI78+k2j2pSMs97YacFJ0XscccBmycT9YtBe+dt1Pc0+AJA0W43VSnhchr2WZalR8MHQKBgEndlCi5AoQ12Bu6J19ptOXk3jYhO/xTXBg3D1KeZ9OQ6CNo7Y4TlDPqBoJRBDz91/Ce0cTD1VFSoAIlXMSINUnv5dFCBmPUzNShrrlSr77GiJP1/kfGpQ6W9kQKBy5w6nVQF/yot/f1T+IuZC26/ZWCrmSEPhH0tfncOFGxrLVBAoGAbeJhpdn2EBmVI9p0j+x4cWW56RR2cgK2s0ZwWKl/HUO11vyyvYU4TwAa0DHYwsXdHd/rg96yVDNwLWKMOZJgX3kp8SMnEyQSIx1e8y46/94lScLKHfWi5puzCegea1FDfK7YOU/bgxHQr4arDosORr4o19xX5BZwaDmlJMm3cx0CgYEAwh+P/tRUfGtjfJexwWSKcxf9Qn0LwAqA/vYd4YDieuUsm4D8u9dRFP8Ypj4ZNDbC/ctRQGlpWxrvZpHAwwOTnOuwVCxvu0jKeHjA7XLihFRteSrXl4vUv8AvmU1dtOXsu1nNwulZBTwuJYARl4oeJMXq5u9r1oxjNGqv+J59H3U=
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAofj4WzNRK/ALtJJI5C4ygHJGtLhZHeH3Pw5Re+nVPp+BPO1Zd0gDCk7gef0Re/J8tkxa9fTVxTxRG141a1duyJQdIYpVYLHeooPSvVOCW5PYhtLxAOJvhNSGsayZoZtZ5vGr3mwQ/rSy1u1W2YVKPHvMphPbbNL1zE0/7gItwrnLmn2MI22ANQ72zm6agBuMl/BDQgaa6kOmk3KIIdYMawrUZfU6IzVala0f6yWsxd4vXrbnf9egC1rfsLz8Zad7SdPiaPQ3y+np0KZNy37Dat3Zj/3o7Ix870oWkfKnKzDHB0XzXXf7B7ycCE19sP97Di34P9CSUlO34rLzJ87OpQIDAQAB
  server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  charset: utf-8
  sign-type: RSA2
  notify-url: http://r34kbu.natappfree.cc/alipay/notify
  return-url: http://r34kbu.natappfree.cc/alipay/returnUrl
