spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tomatomall
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.engine.transaction.internal.TransactionImpl: debug
    org.springframework.transaction: trace
    com.example.tomatomall: debug